service: blockchain-meta-transaction-server

custom:
  stage: ${opt:stage, 'myrtle'}
  region: ${opt:region, 'us-east-2'}
  serverless-offline:
    httpPort: 5021
    noPrependStageInUrl: true
  customDomain:
    domainName: ${opt:stage, 'myrtle'}-meta-tx-server.myrtle.verida.tech
    basePath: ''
    certificateName: '*.myrtle.verida.tech'
    stage: ${opt:stage, 'myrtle'}                                       
    endpointType: regional
    createRoute53Record: true
    apiType: http

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  stage: ${opt:stage, 'myrtle'}
  endpointType: regional
  logs:
    httpApi: true
  httpApi:
    metrics: true
    cors: true
 
functions:
  useContract:
    handler: dist/server.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'
plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-domain-manager