service: blockchain-meta-transaction-server

custom:
  stage: ${opt:stage, 'testnet'}
  region: ${opt:region, 'us-east-1'}

provider:
  name: aws
  runtime: nodejs14.x
  logs:
    httpApi: true
  httpApi:
    metrics: true
    cors: true
 
functions:
  useContract:
    handler: server.handler
    events:
      - httpApi:
          path: '/{proxy+}'
          method: '*'
plugins:
  - serverless-dotenv-plugin